[tool.poetry]
name = "uni_kie"
version = "0.1.0"
description = "Unimodal language models for KIE."
authors = ["ivo-1 <ivoschaper@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
